version: '3.8'
services:
  lgvt-user-service:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    container_name: lgvt-user-service
    networks:
      - lgvt-network
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity  # Let devcontainer take over

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - lgvt-network

networks:
  lgvt-network:
    external: true

volumes:
  postgres-data: